### ISSUE TITLE
Line config breaks and extra colors in empty lines

### ISSUE THREAD

**Issue by nikero41** [TheGLander/indent-rainbowline.nvim#2]
When I add opts from this plugin my line color seems to be bolden, and does not change depending on the scope anymore

Also it seems to add color to black lines because of the adjacent ones

![image](https://github.com/TheGLander/indent-rainbowline.nvim/assets/78855607/650896a9-2897-448b-aed8-5bf553c5c58f)

Here is my config:
```lua
{
	"lukas-reineke/indent-blankline.nvim",
	main = "ibl",
	dependencies = { "TheGLander/indent-rainbowline.nvim" },
	opts = function(_, opts)
		return require("indent-rainbowline").make_opts(
			opts,
			{ color_transparency = 0.05 }
		)
	end,
},
```

Any help?

**Comment by TheGLander** [comment]
Hello! Sorry for the long response time. I think the new commits I pushed right now should fix your first issue, but your second problem is actually a limitation of blankline itself! Blankline only allows for one highlight (or highlight group) to represent an indent, and there's no way to make a different indent highlight group for, say, when there is nothing else on the line. It doesn't bother me too much, but if you want, you can create an issue about it in [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) (maybe @​ing me), and if it gets in, I'll add support for it.

**Comment by nikero41** [comment]
Thanks for fixing it. I works as before with the update.
